export default function Head() {
  return (
    <>
      <title>
        Dr. Humberto Pedrosa - Advogado Especialista em Divórcio | Pensão, Guarda e
        Partilha de Bens
      </title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
